version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env.maria
    ports:
      - "3306:3306"
    #command: bash -c "mysql -h 3306 -u superUser -p'ecommerceUser' -e \"GRANT ALL PRIVILEGES ON *.* TO 'superUser'@'localhost' IDENTIFIED BY 'ecommerceUser'; FLUSH PRIVILEGES;\""