- name: Configure systems
  hosts: "*"
  vars:
    ansible_ssh_private_key_file: ./EcommercekeyVPS
  pre_tasks:
    - name: "install python"
      raw: apt-get -y install python

- name: Call Roles
  hosts: "*"
  vars_files:
  - ansible/vars/vault.yml
  
  roles:
    - role: ansible/roles/aptinstall
    - role: ansible/roles/apacheinstall
    - role: ansible/roles/phpinstall
    - role: ansible/roles/mariadbinstall
    - role: ansible/roles/composersymfonyinstall
    - role: ansible/roles/nodejsinstall
