- name: Configure systems
  hosts: "*"
  vars:
    ansible_ssh_private_key_file: ./EcommercekeyVPS
  pre_tasks:
    - name: Fin de la lecture si l'hôte n'est pas Debian
      ansible.builtin.meta: end_play
      when:
        - ansible_distribution != 'Debian'
    - name: Fin de la lecture si l'hôte n'est pas en version 11
      ansible.builtin.meta: end_play
      when:
        - ansible_distribution_major_version != '11'

    - name: "install python"
      raw: sudo apt-get -y install python3

- name: Call Roles
  hosts: "*"
  become: true
  vars_files:
    - ansible/vars/vault.yml
  pre_tasks:
    - name: Fin de la lecture si l'hôte n'est pas Debian
      ansible.builtin.meta: end_play
      when:
        - ansible_distribution != 'Debian'
    - name: Fin de la lecture si l'hôte n'est pas en version 11
      ansible.builtin.meta: end_play
      when:
        - ansible_distribution_major_version != '11'
  roles:
    - role: ansible/roles/aptinstall
    - role: ansible/roles/phpinstall
    - role: ansible/roles/mariadbinstall
    - role: ansible/roles/nginxinstall

- name: Launch App
  hosts: "*"
  pre_tasks:
    - name: Fin de la lecture si l'hôte n'est pas Debian
      ansible.builtin.meta: end_play
      when:
        - ansible_distribution != 'Debian'
    - name: Fin de la lecture si l'hôte n'est pas en version 11
      ansible.builtin.meta: end_play
      when:
        - ansible_distribution_major_version != '11'
  roles:
    - role: ansible/roles/composersymfonyinstall
    - role: ansible/roles/nodejsinstall
