- name: Configure systems
  hosts: "*"
  vars:
    ansible_ssh_private_key_file: ./EcommercekeyVPS
  pre_tasks:
    - name: "install python"
      raw: sudo apt-get -y install python3

- name: Call Roles
  hosts: "*"
  become: true
  vars_files:
    - ansible/vars/vault.yml
  roles:
    - role: ansible/roles/aptinstall
    - role: ansible/roles/phpinstall
    - role: ansible/roles/mariadbinstall

- name: Launch App
  hosts: "*"
  
  roles:
    - role: ansible/roles/composersymfonyinstall
    - role: ansible/roles/nodejsinstall
