---
# tasks file for nodejsinstall
- name: get nodejs 16
  shell: curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -

- name: Install the nodejs
  become: true
  apt:
    name: 
      - nodejs
    state: present

# move project    change to avoid node module
- name: Copy nuxt project
  become: true
  copy: 
    src: ../../../../client/
    dest: /var/www/client/
    owner: "server"
    group: "server"

- name: Install dependencies
  shell: npm i
  register: npm_finished
  args:
    chdir: /var/www/client

- name: install pm2
  shell: sudo npm install pm2 -g

- name: run with pm2
  shell: pm2 --name clientNuxt start npm -- run dev
  args:
    chdir: /var/www/client