---
# tasks file for nodejsinstall
- name: Install the nodejs and npm
  apt:
    name: 
      - nodejs
      - npm
    state: present

# move project    change to avoid node module
- name: Copy nuxt project
  copy: 
    src: ../../../../client/
    dest: /var/www/client/

- name: Install dependencies
  shell: npm i
  register: npm_finished
  args:
    chdir: /var/www/client

# run   test this but not sure https://www.closingtags.com/deploying-node-js-apps-with-ansible/
- name: Start client
  shell: npm run start
  args:
    chdir: /var/www/client
  ignore_errors: yes
  when: npm_finished.changed