---
# tasks file for composersymfonyinstall

# Install Composer
- name: Install Composer
  command: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

- name: Install Composer
  command: php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

- name: Install Composer
  command: php composer-setup.php

- name: Install Composer
  command: php -r "unlink('composer-setup.php');"

- name: Move Composer.phar
  command: sudo mv composer.phar /usr/local/bin/composer

- name: Get setup.deb.sh for symfony
  shell: curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | sudo -E bash

# Install symfony
- name: install symfony
  become: true
  apt:
    update_cache: yes
    name: 
      - symfony-cli

# - name: Change permissions for app
#   file:
#     path: "/var/app"
#     owner: "server"
#     group: "server"
#     mode: 0770
#     recurse: yes

- name: Copy symfony project
  copy: 
    src: ../../../../app/
    dest: /var/app/
    owner: "server"
    group: "server"

- name: Change owner (Otherwise can't read composer.lock)
  command: sudo chown -R $USER /var/app

# need .env file

# Install dependencies need to create user and change user https://github.com/kirelos/symfony-ansible/blob/master/roles/symfony/tasks/main.yml
- name: Install dependencies
  composer:
    command: install
    working_dir: /var/app
  # environment:
  #   COMPOSER_NO_INTERACTION: "1"   
  #   COMPOSER_ALLOW_SUPERUSER: "1"

#Doctrine migrate

# run


    # - name: Execute migrations
    #   command: "{{ symfony }} doctrine:migrations:migrate --no-interaction"
    #   become: yes
    #   become_user: "{{ sym_user }}"
    #   ignore_errors: yes