---
# tasks file for phpinstall
- name: Install php
  apt:
      name: 
        - php8.2
        - php8.2-mysql
        - php8.2-fpm
        - php8.2-mbstring
        - php8.2-curl
        - php8.2-xml
        - php8.2-zip
      state: present