---
# tasks file for aptinstall
- name: Update apt cache and install package
  apt:
    update_cache: yes
    name: 
      - git
      - curl
      - sudo
      - lsb-release 
      - apt-transport-https 
      - ca-certificates 
      - software-properties-common  
    state: present

- name: Import repository GPG key
  command: sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg 

- name: add repository to sources list
  command: sudo sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'

- name: update
  apt:
    update_cache: yes