on:
  push:
    branches:
      - master
jobs:
  run-playbooks:
    runs-on: self-hosted
    steps:
    - uses: dawidd6/action-ansible-playbook@v2.6.1
    - name: Run Ansible Playbook
      with:
        # Required, playbook filepath
        playbook: playbook.yml
        # Optional, directory where playbooks live
        directory: ./ansible
        # Optional, SSH private key
        key: ${{secrets.EPITECH_MIRROR_SSH_KEY}}
        # Optional, additional flags to pass to ansible-playbook
        options: |
          --inventory .hosts
#https://networkbrouhaha.com/2020/05/ansible-with-github-actions/

