on:
  push:
    branches:
      - feature/setup_ansible
jobs:
  run-playbooks:
    runs-on: ubuntu-22.04
    steps:
    - name: Decrypt Pem
      run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output ./key/EcommercekeyVPS ./key/EcommercekeyVPS.gpg
      env: 
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
    - name: Change right of key file
      run: chmod 600 EcommercekeyVPS
    - uses: actions/checkout@v2
    - name: Run Ansible Playbook
      run: ansible-playbook ./playbook.yml -i ./hosts
#https://networkbrouhaha.com/2020/05/ansible-with-github-actions/

