on:
  push:
    branches:
      - main
jobs:
  run-playbooks:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch depth set to 0 means that all commits are to be mirrored
    - name: Create env
      run: echo "${{ secrets.ENV }}" > ./.env
    - name: Create vault pass
      run: echo "${{ secrets.VAULT_PASS }}" > ./vaul_pass.txt
    - name: Create jwt dir
      run: mkdir jwt
    - name: Create jwt private key
      run: echo "${{ secrets.PRIVATE_JWT }}" > ./jwt/private.pem
    - name: Create jwt public key
      run: echo "${{ secrets.PUBLIC_JWT }}" > ./jwt/public.pem
    - name: Create ssh key
      run: echo "${{ secrets.ECOMMERCEKEYVPS }}" > ./EcommercekeyVPS
    - name: Change right on key
      run: chmod 600 ./EcommercekeyVPS
    - name: Run Ansible Playbook
      run: ansible-playbook ./playbook.yml -i ./hosts
#https://networkbrouhaha.com/2020/05/ansible-with-github-actions/

