on:
  push:
    branches:
      - master
jobs:
  run-playbooks:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Ansible Playbook
      run: ansible-playbook ./ansible/playbook.yml -i ./ansible/hosts
#https://networkbrouhaha.com/2020/05/ansible-with-github-actions/

